server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Georgui716371/microservicios-springboot
          search-paths: config-data
  application:
    name: service-config

 

